const __vite__mapDeps=(i,m=__vite__mapDeps,d=(m.f||(m.f=[window.OC.filePath('files_pdfviewer', '', 'js/opensheetmusicdisplay.min-B-2B5fv8.chunk.mjs'),window.OC.filePath('files_pdfviewer', '', 'js/logger-CRuRhkXk.chunk.mjs')])))=>i.map(i=>d[i]);
import{d as y,z as v,A as _,f as h,i as x,o as S,c as W,b as k,j as C,h as A,_ as D}from"./logger-CRuRhkXk.chunk.mjs";import{c as E}from"./index-ClEY3Gs5.chunk.mjs";import{l as m,t as M}from"./files_pdfviewer-main.mjs";import{_ as O}from"./_plugin-vue_export-helper-B4pKF6H2.chunk.mjs";(function(){try{if(typeof document<"u"){var i=document.createElement("style");i.appendChild(document.createTextNode(`.sheetmusic[data-v-5f237c2b] {
	overflow: auto;
}
.sheetmusic__sheet[data-v-5f237c2b] {
	/* The renderer draws onto a white page, which needs its own ground
	   rather than the viewer's dark backdrop showing through the staves */
	margin: 0 auto;
	padding: 16px;
	max-width: 1200px;
	background-color: #fff;
}`)),document.head.appendChild(i)}}catch(n){console.error("vite-plugin-css-injected-by-js",n)}})();const T=y({name:"ViewerSheetmusic",__name:"Sheetmusic",props:{file:{},files:{},maxHeight:{},maxWidth:{},editing:{type:Boolean},isSidebarShown:{type:Boolean},turns:{},localSource:{}},emits:["loaded","errored","update:canSwipe","update:editing","update:playing"],setup(i,{emit:n}){const a=i,c=n,u=v("sheet"),p=A(()=>({width:`${a.maxWidth}px`,height:`${a.maxHeight}px`}));let r=null,s=null;async function f(e){for(let t=0;t<30;t++){if(e.offsetWidth>0)return e.offsetWidth;await new Promise(o=>requestAnimationFrame(o))}return e.offsetWidth}async function l(){s?.abort(),s=new AbortController;const{signal:e}=s,t=u.value;if(t!==null)try{const{OpenSheetMusicDisplay:o}=await D(async()=>{const{OpenSheetMusicDisplay:b}=await import("./opensheetmusicdisplay.min-B-2B5fv8.chunk.mjs").then(g=>g.o);return{OpenSheetMusicDisplay:b}},__vite__mapDeps([0,1]),import.meta.url),w=await E.get(a.file.encodedSource,{responseType:"blob",signal:e});if(e.aborted)return;r?.clear();const d=new o(t,{autoResize:!0,darkMode:!0});if(await d.load(w.data),e.aborted||(r=d,c("loaded"),await f(t),e.aborted))return;d.render()}catch(o){if(e.aborted)return;m.error("Could not render the sheet music",{error:o}),c("errored",new Error(M("Failed to load sheet music.")))}}return _(()=>{l()}),h(()=>a.file.source,()=>{l()}),h([()=>a.maxWidth,()=>a.maxHeight],()=>{try{r?.render()}catch(e){m.debug("Could not redraw the sheet music at the new size",{error:e})}}),x(()=>{s?.abort(),r?.clear(),r=null}),(e,t)=>(S(),W("div",{class:"sheetmusic",style:C(p.value)},[k("div",{ref_key:"sheet",ref:u,class:"sheetmusic__sheet"},null,512)],4))}}),V=O(T,[["__scopeId","data-v-5f237c2b"]]);export{V as default};
//# sourceMappingURL=Sheetmusic-BQeURbwJ.chunk.mjs.map
