# SPDX-FileCopyrightText: 2014 ownCloud, Inc.
# SPDX-License-Identifier: AGPL-3.0-only
filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'

imports:
    - javascript
    - php

tools:
    external_code_coverage: true
