# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
#
# SPDX-FileCopyrightText: 2021-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Node

on:
  pull_request:
    paths-ignore:
      - '.github/workflows/**'
      - 'src/**'
      - 'appinfo/info.xml'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '**.js'
      - '**.ts'
      - '**.vue'
  push:
    branches:
      - main
      - master
      - stable*

concurrency:
  group: node-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: none

    runs-on: ubuntu-latest

    name: node
    steps:
      - name: Skip
        run: 'echo "No JS/TS files changed, skipped Node"'
